<?php

/**
 * Dezato Cake House - Karachi storefront content.
 */
return [
    'brand' => [
        'name' => 'Dezato Cake House',
        'tagline' => 'Handcrafted cakes & desserts in Karachi',
        'phone' => '+92 300 0000000',
        'email' => 'hello@dezato.pk',
        'city' => 'Karachi',
        'country' => 'Pakistan',
        'currency' => 'PKR',
        'founded' => 2018,
    ],

    'nav' => [
        ['label' => 'Home', 'route' => 'home'],
        ['label' => 'About Us', 'route' => 'about'],
        ['label' => 'Our Services', 'route' => 'services'],
        ['label' => 'Cake Customization', 'route' => 'customization'],
    ],

    'home' => [
        'announcement' => 'Pickup & delivery across Karachi',
        'products' => [
            ['label' => 'Cakes 2.5 lbs', 'image' => 'images/home/delivery-pickup.png', 'href' => '/menu?category=cakes', 'tone' => 'mint'],
            ['label' => 'Cupcakes', 'image' => 'images/home/promo-workshop.jpg', 'href' => '/menu?category=cupcakes', 'tone' => 'blue'],
            ['label' => 'Cheesecakes', 'image' => 'images/home/promo-anniversary.jpg', 'href' => '/menu?category=cheesecakes', 'tone' => 'cream'],
            ['label' => 'Eclairs', 'image' => 'images/home/promo-seasonal.jpg', 'href' => '/menu?category=eclairs', 'tone' => 'lilac'],
            ['label' => 'Brownies', 'image' => 'images/home/promo-cookbook.jpg', 'href' => '/menu?category=brownies', 'tone' => 'pink'],
            ['label' => 'Sundaes', 'image' => 'images/home/promo-pudding.jpg', 'href' => '/menu?category=sundaes', 'tone' => 'pink'],
            ['label' => 'Tarts', 'image' => 'images/home/promo-catering.png', 'href' => '/menu?category=tarts', 'tone' => 'cream'],
            ['label' => 'Mini Pies', 'image' => 'images/home/delivery-ship.png', 'href' => '/menu?category=mini-pies', 'tone' => 'mint'],
        ],
        'occasions' => [
            ['label' => 'Birthdays', 'image' => 'images/home/hero.jpg', 'href' => '/menu?category=cakes'],
            ['label' => 'Office Treats', 'image' => 'images/home/promo-catering.png', 'href' => '/our-services'],
            ['label' => 'Custom Cakes', 'image' => 'images/home/promo-anniversary.jpg', 'href' => '/cake-customization'],
            ['label' => 'Gifting', 'image' => 'images/home/delivery-ship.png', 'href' => '/menu'],
        ],
    ],

    'shipping' => [
        'fee' => 499,
        'eta' => '2–4 business days within Pakistan',
        'label' => 'Pakistan Courier',
    ],

    'menu' => [
        'categories' => [
            ['id' => 'all', 'label' => 'All'],
            ['id' => 'cakes', 'label' => "Cake's 2.5lbs"],
            ['id' => 'cupcakes', 'label' => 'Cupcakes'],
            ['id' => 'cheesecakes', 'label' => 'Cheesecakes'],
            ['id' => 'brownies', 'label' => 'Brownies'],
            ['id' => 'eclairs', 'label' => 'Eclairs'],
            ['id' => 'sundaes', 'label' => 'Sundaes'],
            ['id' => 'tarts', 'label' => 'Tarts'],
            ['id' => 'mini-pies', 'label' => 'Mini Pies'],
        ],
        'products' => [
            // -- Cakes 2.5 lbs (14) --
            [
                'id' => 'coffee-chocolate-cake',
                'name' => 'Coffee Chocolate Cake',
                'category' => 'cakes',
                'price' => 1500,
                'badge' => null,
                'weight' => '2.5 lbs',
                'description' => 'Soft coffee sponge layered with chocolate frosting - a 2.5 lb favourite for everyday celebrations.',
                'image' => 'images/home/delivery-pickup.png',
            ],
            [
                'id' => 'chocolate-mousse-cake',
                'name' => 'Chocolate Mousse Cake',
                'category' => 'cakes',
                'price' => 1650,
                'badge' => 'Popular',
                'weight' => '2.5 lbs',
                'description' => 'Light chocolate mousse over a tender cocoa base, finished for a clean slice every time.',
                'image' => 'images/home/promo-pudding.jpg',
            ],
            [
                'id' => 'chocolate-heaven-cake',
                'name' => 'Chocolate Heaven Cake',
                'category' => 'cakes',
                'price' => 1700,
                'badge' => 'Bestseller',
                'weight' => '2.5 lbs',
                'description' => 'Deep chocolate layers with a rich finish - one of our most ordered 2.5 lb cakes in Karachi.',
                'image' => 'images/home/hero.jpg',
            ],
            [
                'id' => 'milky-malt-cake',
                'name' => 'Milky Malt Cake',
                'category' => 'cakes',
                'price' => 1700,
                'badge' => null,
                'weight' => '2.5 lbs',
                'description' => 'Creamy malt flavour in a soft, moist crumb - comfort dessert done right.',
                'image' => 'images/home/promo-seasonal.jpg',
            ],
            [
                'id' => 'cadbury-chocolate-cake',
                'name' => 'Cadbury Chocolate Cake',
                'category' => 'cakes',
                'price' => 1850,
                'badge' => null,
                'weight' => '2.5 lbs',
                'description' => 'Chocolate cake inspired by classic Cadbury richness, finished with a smooth chocolate cream.',
                'image' => 'images/home/promo-cookbook.jpg',
            ],
            [
                'id' => 'chocolate-fudge-cake',
                'name' => 'Chocolate Fudge Cake',
                'category' => 'cakes',
                'price' => 1950,
                'badge' => null,
                'weight' => '2.5 lbs',
                'description' => 'Dense chocolate fudge layers with a glossy finish - for serious chocolate lovers.',
                'image' => 'images/home/promo-workshop.jpg',
            ],
            [
                'id' => 'chocolate-malt-cake',
                'name' => 'Chocolate Malt Cake',
                'category' => 'cakes',
                'price' => 2000,
                'badge' => null,
                'weight' => '2.5 lbs',
                'description' => 'Chocolate and malt in one 2.5 lb cake - soft sponge, creamy frosting.',
                'image' => 'images/home/promo-anniversary.jpg',
            ],
            [
                'id' => 'nutella-cake',
                'name' => 'Nutella Cake',
                'category' => 'cakes',
                'price' => 2100,
                'badge' => null,
                'weight' => '2.5 lbs',
                'description' => 'Hazelnut-chocolate layers finished with Nutella cream.',
                'image' => 'images/home/delivery-catering.png',
            ],
            [
                'id' => 'red-velvet-cake',
                'name' => 'Red Velvet Cake',
                'category' => 'cakes',
                'price' => 2100,
                'badge' => null,
                'weight' => '2.5 lbs',
                'description' => 'Cocoa-kissed red velvet with cream cheese frosting - birthday classic.',
                'image' => 'images/home/promo-anniversary.jpg',
            ],
            [
                'id' => 'three-milk-cake',
                'name' => 'Three Milk Cake',
                'category' => 'cakes',
                'price' => 2100,
                'badge' => 'Popular',
                'weight' => '2.5 lbs',
                'description' => 'Tres leches-style cake soaked in three milks, topped with whipped cream.',
                'image' => 'images/home/promo-pudding.jpg',
            ],
            [
                'id' => 'ferrero-classic-cake',
                'name' => 'Ferrero Classic Cake',
                'category' => 'cakes',
                'price' => 2250,
                'badge' => 'Signature',
                'weight' => '2.5 lbs',
                'description' => 'Hazelnut chocolate cake with Ferrero-inspired crunch and cream.',
                'image' => 'images/home/promo-catering.png',
            ],
            [
                'id' => 'salted-caramel-cake',
                'name' => 'Salted Caramel Cake',
                'category' => 'cakes',
                'price' => 2300,
                'badge' => null,
                'weight' => '2.5 lbs',
                'description' => 'Moist layers with salted caramel cream and a sweet drizzle finish.',
                'image' => 'images/home/promo-seasonal.jpg',
            ],
            [
                'id' => 'lotus-cake',
                'name' => 'Lotus Cake',
                'category' => 'cakes',
                'price' => 2500,
                'badge' => 'Guest favorite',
                'weight' => '2.5 lbs',
                'description' => 'Biscoff / Lotus cream cake with caramelised cookie notes throughout.',
                'image' => 'images/home/hero.jpg',
            ],
            [
                'id' => 'raffaello-cake',
                'name' => 'Raffaello Cake',
                'category' => 'cakes',
                'price' => 2500,
                'badge' => null,
                'weight' => '2.5 lbs',
                'description' => 'Coconut and white chocolate layers with a Raffaello-inspired finish.',
                'image' => 'images/home/delivery-ship.png',
            ],

            // -- Cupcakes (10) --
            [
                'id' => 'red-velvet-cupcake',
                'name' => 'Red Velvet Cupcake',
                'category' => 'cupcakes',
                'price' => 300,
                'badge' => null,
                'description' => 'Moist red velvet topped with cream cheese frosting. Sold per piece.',
                'image' => 'images/home/promo-workshop.jpg',
            ],
            [
                'id' => 'salted-caramel-cupcake',
                'name' => 'Salted Caramel Cupcake',
                'category' => 'cupcakes',
                'price' => 300,
                'badge' => null,
                'description' => 'Soft cupcake with salted caramel frosting. Sold per piece.',
                'image' => 'images/home/promo-seasonal.jpg',
            ],
            [
                'id' => 'malt-cupcake',
                'name' => 'Malt Cupcake',
                'category' => 'cupcakes',
                'price' => 300,
                'badge' => null,
                'description' => 'Malt-flavoured cupcake with creamy frosting. Sold per piece.',
                'image' => 'images/home/promo-pudding.jpg',
            ],
            [
                'id' => 'mm-cupcake',
                'name' => 'M&M Cupcake',
                'category' => 'cupcakes',
                'price' => 300,
                'badge' => null,
                'description' => 'Chocolate cupcake topped with candy-coated chocolate pieces. Sold per piece.',
                'image' => 'images/home/hero.jpg',
            ],
            [
                'id' => 'hazelnut-cupcake',
                'name' => 'Hazelnut Cupcake',
                'category' => 'cupcakes',
                'price' => 300,
                'badge' => null,
                'description' => 'Hazelnut sponge with creamy frosting and a nutty finish. Sold per piece.',
                'image' => 'images/home/promo-cookbook.jpg',
            ],
            [
                'id' => 'oreo-cupcake',
                'name' => 'Oreo Cupcake',
                'category' => 'cupcakes',
                'price' => 300,
                'badge' => null,
                'description' => 'Cookies-and-cream cupcake with Oreo crumbs. Sold per piece.',
                'image' => 'images/home/promo-anniversary.jpg',
            ],
            [
                'id' => 'lotus-cupcake',
                'name' => 'Lotus Cupcake',
                'category' => 'cupcakes',
                'price' => 300,
                'badge' => 'Popular',
                'description' => 'Lotus Biscoff cream on a soft vanilla base. Sold per piece.',
                'image' => 'images/home/promo-catering.png',
            ],
            [
                'id' => 'swiss-dark-cupcake',
                'name' => 'Swiss Dark Cupcake',
                'category' => 'cupcakes',
                'price' => 300,
                'badge' => null,
                'description' => 'Dark chocolate cupcake with a rich cocoa finish. Sold per piece.',
                'image' => 'images/home/delivery-pickup.png',
            ],
            [
                'id' => 'ferrero-cupcake',
                'name' => 'Ferrero Cupcake',
                'category' => 'cupcakes',
                'price' => 300,
                'badge' => null,
                'description' => 'Hazelnut chocolate cupcake with Ferrero-style topping. Sold per piece.',
                'image' => 'images/home/delivery-catering.png',
            ],
            [
                'id' => 'coffee-cupcake',
                'name' => 'Coffee Cupcake',
                'category' => 'cupcakes',
                'price' => 300,
                'badge' => null,
                'description' => 'Coffee-infused cupcake with a light cream swirl. Sold per piece.',
                'image' => 'images/home/delivery-ship.png',
            ],

            // -- Cheesecakes (3) --
            [
                'id' => 'new-york-cheesecake',
                'name' => 'New York Cheese Cake',
                'category' => 'cheesecakes',
                'price' => 2500,
                'badge' => 'Bestseller',
                'weight' => '2.5 lbs',
                'description' => 'Dense, creamy New York-style cheesecake - a Dezato favourite.',
                'image' => 'images/home/promo-anniversary.jpg',
            ],
            [
                'id' => 'caramel-cheesecake',
                'name' => 'Caramel Cheese Cake',
                'category' => 'cheesecakes',
                'price' => 2500,
                'badge' => null,
                'weight' => '2.5 lbs',
                'description' => 'Baked cheesecake finished with a salted caramel layer.',
                'image' => 'images/home/promo-seasonal.jpg',
            ],
            [
                'id' => 'lotus-cheesecake',
                'name' => 'Lotus Cheese Cake',
                'category' => 'cheesecakes',
                'price' => 2500,
                'badge' => null,
                'weight' => '2.5 lbs',
                'description' => 'Creamy cheesecake with Lotus Biscoff crust and cream.',
                'image' => 'images/home/hero.jpg',
            ],

            // -- Brownies (2) --
            [
                'id' => 'fudge-brownie',
                'name' => 'Fudge Brownie',
                'category' => 'brownies',
                'price' => 500,
                'badge' => null,
                'description' => 'Dense chocolate brownie with a glossy crackle top.',
                'image' => 'images/home/promo-cookbook.jpg',
            ],
            [
                'id' => 'nutella-brownie',
                'name' => 'Nutella Brownie',
                'category' => 'brownies',
                'price' => 550,
                'badge' => 'Popular',
                'description' => 'Fudgy brownie swirled with Nutella.',
                'image' => 'images/home/promo-workshop.jpg',
            ],

            // -- Eclairs (3) --
            [
                'id' => 'chocolate-eclair',
                'name' => 'Chocolate Eclair',
                'category' => 'eclairs',
                'price' => 300,
                'badge' => null,
                'description' => 'Choux pastry filled with cream and finished with chocolate. Sold per piece.',
                'image' => 'images/home/delivery-pickup.png',
            ],
            [
                'id' => 'caramel-eclair',
                'name' => 'Caramel Eclair',
                'category' => 'eclairs',
                'price' => 300,
                'badge' => 'Popular',
                'description' => 'Classic eclair with caramel cream and glaze. Sold per piece.',
                'image' => 'images/home/promo-seasonal.jpg',
            ],
            [
                'id' => 'lotus-eclair',
                'name' => 'Lotus Eclair',
                'category' => 'eclairs',
                'price' => 300,
                'badge' => null,
                'description' => 'Eclair filled with Lotus cream. Sold per piece.',
                'image' => 'images/home/promo-catering.png',
            ],

            // -- Sundaes (2) --
            [
                'id' => 'three-milk-sundae',
                'name' => 'Three Milk Sundae',
                'category' => 'sundaes',
                'price' => 350,
                'badge' => null,
                'description' => 'Cup sundae inspired by three-milk cake. Sold per piece.',
                'image' => 'images/home/promo-pudding.jpg',
            ],
            [
                'id' => 'oreo-sundae',
                'name' => 'Oreo Sundae',
                'category' => 'sundaes',
                'price' => 350,
                'badge' => null,
                'description' => 'Creamy Oreo sundae cup. Sold per piece.',
                'image' => 'images/home/promo-anniversary.jpg',
            ],

            // -- Tarts (2) --
            [
                'id' => 'fruit-tart',
                'name' => 'Fruit Tart',
                'category' => 'tarts',
                'price' => 400,
                'badge' => null,
                'description' => 'Buttery tart shell with pastry cream and seasonal fruit.',
                'image' => 'images/home/promo-seasonal.jpg',
            ],
            [
                'id' => 'chocolate-tart',
                'name' => 'Chocolate Tart',
                'category' => 'tarts',
                'price' => 400,
                'badge' => null,
                'description' => 'Crisp tart shell filled with smooth chocolate ganache.',
                'image' => 'images/home/promo-cookbook.jpg',
            ],

            // -- Mini Pies (2) --
            [
                'id' => 'walnut-pie',
                'name' => 'Walnut Pie',
                'category' => 'mini-pies',
                'price' => 300,
                'badge' => null,
                'description' => 'Mini pie filled with crunchy walnuts and a hint of vanilla.',
                'image' => 'images/home/delivery-ship.png',
            ],
            [
                'id' => 'chocolate-mini-pie',
                'name' => 'Chocolate Mini Pie',
                'category' => 'mini-pies',
                'price' => 300,
                'badge' => null,
                'description' => 'Individual chocolate pie with a flaky crust.',
                'image' => 'images/home/promo-workshop.jpg',
            ],
        ],
    ],

    'locations' => [
        [
            'id' => 'dha-phase-6',
            'name' => 'DHA Phase 6',
            'city' => 'Karachi',
            'region' => 'Sindh',
            'address' => 'Plot 27-E, Khayaban-e-Seher Commercial, Phase 6, DHA',
            'hours' => 'Mon–Tue & Sat 10:00 AM – 11:00 PM · Wed–Fri 10:00 AM – 10:00 PM · Sun 9:00 AM – 11:00 PM',
            'phone' => '+92 300 0000000',
            'services' => ['Pickup', 'Delivery', 'Custom cakes'],
            'delivers' => true,
            'delivery_fee' => 199,
            'image' => 'images/home/delivery-pickup.png',
        ],
        [
            'id' => 'gizri',
            'name' => 'Gizri',
            'city' => 'Karachi',
            'region' => 'Sindh',
            'address' => 'Plot 4D/2, Shop 1, Gizri Boulevard, Phase 4, DHA',
            'hours' => 'Mon 9:00 AM – 10:45 PM · Tue–Sun 9:00 AM – 11:00 PM',
            'phone' => '+92 300 0000000',
            'services' => ['Pickup', 'Delivery', 'Catering'],
            'delivers' => true,
            'delivery_fee' => 199,
            'image' => 'images/home/hero.jpg',
        ],
    ],

    'services' => [
        'packages' => [
            [
                'title' => 'Office Sweet Box',
                'serves' => 'Serves 12–15',
                'price' => 'From ₨ 7,500',
                'blurb' => 'Assorted cupcakes, brownies, and eclairs for meetings and team treats.',
                'image' => 'images/home/promo-catering.png',
            ],
            [
                'title' => 'Celebration Dessert Table',
                'serves' => 'Serves 25–40',
                'price' => 'From ₨ 22,000',
                'blurb' => 'Cakes, cupcakes, and sundae cups styled for birthdays and mehndi gatherings.',
                'image' => 'images/home/delivery-catering.png',
            ],
            [
                'title' => 'Corporate Gifting',
                'serves' => 'Custom packs',
                'price' => 'From ₨ 4,500',
                'blurb' => 'Boxed treats for clients and teams across Karachi.',
                'image' => 'images/home/delivery-ship.png',
            ],
        ],
    ],

    'about' => [
        'intro' => 'Dezato Cake House started in Karachi with one goal: bake desserts that taste as good as they look. From 2.5 lb celebration cakes to cupcakes, eclairs, and cheesecakes, everything is made fresh for pickup and delivery across the city.',
        'milestones' => [
            [
                'year' => '2018',
                'title' => 'First oven in Karachi',
                'text' => 'Dezato Cake House opens with a small counter and a focus on handcrafted cakes.',
            ],
            [
                'year' => '2020',
                'title' => 'Signature flavours take hold',
                'text' => 'Lotus, Ferrero, three-milk, and chocolate heaven become guest favourites across DHA.',
            ],
            [
                'year' => '2023',
                'title' => 'More tables, same craft',
                'text' => 'A second Karachi counter opens so more neighbourhoods can order fresh.',
            ],
            [
                'year' => '2026',
                'title' => 'Custom & catering ready',
                'text' => 'Cake customization, catering boxes, and citywide delivery for every celebration.',
            ],
        ],
    ],

    'customization' => [
        'options' => [
            ['title' => 'Flavour & filling', 'text' => 'Choose from chocolate, red velvet, lotus, three milk, and more.'],
            ['title' => 'Size & servings', 'text' => 'From 2.5 lb cakes to cupcake boxes sized for your guest list.'],
            ['title' => 'Message & finish', 'text' => 'Inscriptions, colour themes, and simple décor for birthdays and events.'],
        ],
    ],

    'order' => [
        'options' => [
            [
                'title' => 'Pickup or Delivery',
                'text' => 'Choose a Karachi bakery, then order fresh treats for pickup or local delivery.',
                'cta' => 'Choose location',
                'route' => 'order.start',
                'image' => 'images/home/delivery-pickup.png',
            ],
            [
                'title' => 'Pakistan Courier',
                'text' => 'Fresh bakery favourites packed carefully for delivery across Pakistan.',
                'cta' => 'Ship to me',
                'route' => 'order.start',
                'image' => 'images/home/delivery-ship.png',
            ],
            [
                'title' => 'Catering & Events',
                'text' => 'Dessert tables, office boxes, and custom cake orders for your occasion.',
                'cta' => 'View services',
                'route' => 'services',
                'image' => 'images/home/delivery-catering.png',
            ],
        ],
    ],
];
